"""Add mark for edit Task text

Revision ID: 993f28fb18fb
Revises: ceb139e2c287
Create Date: 2024-12-01 18:52:26.700861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993f28fb18fb'
down_revision = 'ceb139e2c287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_is_edited', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('text_is_edited')

    # ### end Alembic commands ###
